### ISSUE TITLE
fatal bug in setup-instructor-resources

### ISSUE THREAD

**Issue by danverde** [byuitechops/setup-instructor-resources#20]
```
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\setup-instructor-resources\main.js:368
            instructorResourcesId = instructorResourcesObj.id;
                                                           ^

TypeError: Cannot read property 'id' of undefined
    at canvas.getModules (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\setup-instructor-resources\main.js:368:60)
    at paginate (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:40:13)
    at Object.callReturned [as callback] (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:216:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:2257:31
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at updateRateLimit (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:111:17)
    at updateRateLimit (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:58:13)
    at Request.request [as _callback] (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:99:13)
    at Request.self.callback (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
```

**Comment by csammcgrath** [comment]
Fixed.
